### ISSUE TITLE
I want to use this in localhost

### ISSUE THREAD

**Issue by tomoyukikino** [ariga/entviz#3]
I try to run below command. but this url can see anyone.
```bash
❯ go run -mod=mod ariga.io/entviz ./ent/schema
Here is a public link to your schema visualization
        https://gh.atlasgo.cloud/explore/c3aa3f24
```

I want this ERD can see team member only.

**Comment by rotemtam** [comment]
Hi @tomoyukikino 

Thanks for reaching out.

We don't plan to create a localhost version anytime soon. 

You can currently create private schema visualizations by creating an account on atlasgo.cloud and we will work on supporting this flow via EntViz (using an API token).

How does this sound?

**Comment by tomoyukikino** [comment]
Thanks for comment me.
Okey, I waiting to releases the new version.
